/**
 * Open practice content. Every item here is originally authored for this
 * project and released under the repository's MIT licence, so the dataset can
 * be redistributed and cited without any licensing friction.
 */

/** A writing task prompt. */
export interface WritingPrompt {
  readonly id: string;
  readonly module: 'academic' | 'general';
  readonly task: 1 | 2;
  readonly topic: string;
  readonly prompt: string;
  readonly minimumWords: number;
  readonly suggestedMinutes: number;
}

/** A speaking prompt covering all three parts of the interview. */
export interface SpeakingPrompt {
  readonly id: string;
  readonly part: 1 | 2 | 3;
  readonly topic: string;
  readonly questions: readonly string[];
}

/** A reading passage with comprehension items. */
export interface ReadingPassage {
  readonly id: string;
  readonly title: string;
  readonly module: 'academic' | 'general';
  readonly wordCount: number;
  readonly text: string;
  readonly questions: readonly {
    readonly id: string;
    readonly type: 'true-false-notgiven' | 'multiple-choice' | 'short-answer';
    readonly question: string;
    readonly options?: readonly string[];
    readonly answer: string;
  }[];
}

/** Writing prompts across both modules and both tasks. */
export const WRITING_PROMPTS: readonly WritingPrompt[] = [
  {
    id: 'w-a1-001',
    module: 'academic',
    task: 1,
    topic: 'urbanisation',
    prompt:
      'The chart below shows the percentage of people living in cities in four countries between 1980 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.',
    minimumWords: 150,
    suggestedMinutes: 20,
  },
  {
    id: 'w-a1-002',
    module: 'academic',
    task: 1,
    topic: 'energy',
    prompt:
      'The diagram illustrates how electricity is generated by a hydroelectric dam. Summarise the information by selecting and reporting the main features.',
    minimumWords: 150,
    suggestedMinutes: 20,
  },
  {
    id: 'w-a2-001',
    module: 'academic',
    task: 2,
    topic: 'education',
    prompt:
      'Some people believe that university education should be free for all students, while others argue that students should pay their own fees. Discuss both views and give your own opinion.',
    minimumWords: 250,
    suggestedMinutes: 40,
  },
  {
    id: 'w-a2-002',
    module: 'academic',
    task: 2,
    topic: 'environment',
    prompt:
      'Individual action is not enough to address climate change; only government regulation can deliver meaningful reductions in emissions. To what extent do you agree or disagree?',
    minimumWords: 250,
    suggestedMinutes: 40,
  },
  {
    id: 'w-g1-001',
    module: 'general',
    task: 1,
    topic: 'letters',
    prompt:
      'You recently stayed in a hotel and were unhappy with the service. Write a letter to the manager. In your letter explain why you stayed there, describe the problems, and say what action you would like the manager to take.',
    minimumWords: 150,
    suggestedMinutes: 20,
  },
  {
    id: 'w-g2-001',
    module: 'general',
    task: 2,
    topic: 'work',
    prompt:
      'In many countries employees are now able to work from home for part of the week. Do the advantages of this development outweigh the disadvantages?',
    minimumWords: 250,
    suggestedMinutes: 40,
  },
];

/** Speaking prompts for parts 1-3. */
export const SPEAKING_PROMPTS: readonly SpeakingPrompt[] = [
  {
    id: 's-p1-001',
    part: 1,
    topic: 'hometown',
    questions: [
      'Where is your hometown?',
      'What do you like most about it?',
      'Has your hometown changed much in recent years?',
      'Would you like to live there in the future?',
    ],
  },
  {
    id: 's-p1-002',
    part: 1,
    topic: 'technology',
    questions: [
      'How often do you use a computer?',
      'What kind of applications do you use most?',
      'Do you think you spend too much time online?',
    ],
  },
  {
    id: 's-p2-001',
    part: 2,
    topic: 'a memorable journey',
    questions: [
      'Describe a journey that you remember well. You should say: where you went, who you travelled with, what happened during the journey, and explain why you remember it.',
    ],
  },
  {
    id: 's-p2-002',
    part: 2,
    topic: 'a skill you learned',
    questions: [
      'Describe a skill that took you a long time to learn. You should say: what the skill is, how you learned it, how long it took, and explain how it has been useful to you.',
    ],
  },
  {
    id: 's-p3-001',
    part: 3,
    topic: 'travel and society',
    questions: [
      'How has international travel changed the way people see the world?',
      'Do you think tourism always benefits local communities?',
      'Should governments limit travel to protect the environment?',
    ],
  },
];

/** Reading passages with answer keys. */
export const READING_PASSAGES: readonly ReadingPassage[] = [
  {
    id: 'r-a-001',
    title: 'The Quiet Return of the Urban Tram',
    module: 'academic',
    wordCount: 118,
    text: 'Trams disappeared from most Western cities during the middle of the twentieth century, displaced by buses and private cars. In the last three decades, however, planners have rediscovered them. Modern light-rail vehicles are quiet, accessible and comparatively cheap to operate once the track is laid. Cities from Bordeaux to Melbourne report that the arrival of a tram line raises the value of adjacent property and shifts a measurable share of commuters away from cars. Critics note that construction disrupts businesses for months and that the capital cost per kilometre remains high. Nonetheless, where population density is sufficient, the operating economics of trams tend to improve steadily over a thirty-year horizon.',
    questions: [
      {
        id: 'r-a-001-q1',
        type: 'true-false-notgiven',
        question:
          'Trams were removed from many Western cities because of competition from cars and buses.',
        answer: 'true',
      },
      {
        id: 'r-a-001-q2',
        type: 'true-false-notgiven',
        question: 'Tram construction is cheaper per kilometre than building a road.',
        answer: 'not given',
      },
      {
        id: 'r-a-001-q3',
        type: 'short-answer',
        question: 'Over what period do tram operating economics tend to improve?',
        answer: 'thirty years',
      },
    ],
  },
  {
    id: 'r-g-001',
    title: 'Community Library Notice',
    module: 'general',
    wordCount: 74,
    text: 'The community library is open from 9am to 7pm on weekdays and from 10am to 4pm on Saturdays. Membership is free for all residents; proof of address is required at registration. Members may borrow up to eight items for three weeks, and loans can be renewed twice online unless another member has reserved the item. Late returns incur no fine, but borrowing rights are suspended until overdue items are returned.',
    questions: [
      {
        id: 'r-g-001-q1',
        type: 'multiple-choice',
        question: 'How many items may a member borrow at one time?',
        options: ['Three', 'Six', 'Eight', 'Twelve'],
        answer: 'Eight',
      },
      {
        id: 'r-g-001-q2',
        type: 'true-false-notgiven',
        question: 'Members are charged a fee when items are returned late.',
        answer: 'false',
      },
    ],
  },
];
